services:
  web:
    image: nginx:alpine
    ports:
      - "8082:80"
    volumes:
      - ../images/site:/usr/share/nginx/html:ro
    healthcheck:
      test: ["CMD-SHELL","wget -qO- http://127.0.0.1 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: unless-stopped
